# JSX support via GraalVM:
app.ssr.resource=classpath:/static/fe/ssr.js
app.ssr.entryfunction=renderPage

# HSQLDB in-memory database
spring.datasource.url=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=

# Disable Boot SQL init (REQUIRED in Boot 4):
spring.sql.init.mode=never
